<?php

use Illuminate\Support\Str;

dataset('protected_routes', [
    ['GET', '/api/auth/profile'],
    ['PUT', '/api/auth/profile'],
    ['PUT', '/api/auth/profile/password'],
    ['POST', '/api/auth/logout'],
    ['POST', '/api/email/verification-notification'],
    ['POST', '/api/email/resend'],
    ['GET', '/api/email/verify/1/'.Str::random(40)],
    ['GET', '/api/user'],
    ['POST', '/api/logout'],
    ['GET', '/api/workspaces'],
    ['POST', '/api/workspaces'],
    ['GET', '/api/workspaces/test-slug'],
    ['PUT', '/api/workspaces/1'],
    ['DELETE', '/api/workspaces/1'],
    ['POST', '/api/workspaces/1/invite'],
    ['PATCH', '/api/workspaces/accept-invitation'],
    ['DELETE', '/api/workspaces/1/users'],
    ['GET', '/api/workspaces/1/boards'],
    ['POST', '/api/workspaces/1/boards'],
    ['GET', '/api/workspaces/1/boards/1'],
    ['PUT', '/api/workspaces/1/boards/1'],
    ['PATCH', '/api/workspaces/1/boards/1'],
    ['DELETE', '/api/workspaces/1/boards/1'],
    ['PATCH', '/api/workspaces/1/boards/1/reorder'],
    ['PATCH', '/api/workspaces/1/boards/1/toggle-favorite'],
    ['POST', '/api/workspaces/1/boards/1/cards'],
    ['GET', '/api/workspaces/1/boards/1/cards/1'],
    ['PUT', '/api/workspaces/1/boards/1/cards/1'],
    ['PATCH', '/api/workspaces/1/boards/1/cards/1'],
    ['DELETE', '/api/workspaces/1/boards/1/cards/1'],
    ['GET', '/api/workspaces/test-slug/labels'],
    ['POST', '/api/workspaces/test-slug/labels'],
    ['GET', '/api/workspaces/test-slug/labels/1'],
    ['PUT', '/api/workspaces/test-slug/labels/1'],
    ['PATCH', '/api/workspaces/test-slug/labels/1'],
    ['DELETE', '/api/workspaces/test-slug/labels/1'],
    ['POST', '/api/cards/attach-label'],
    ['POST', '/api/cards/detach-label'],
    ['GET', '/api/cards/1/labels'],
    ['GET', '/api/cards/1/assignees'],
    ['POST', '/api/cards/1/assignees'],
    ['DELETE', '/api/cards/1/assignees/1'],
    ['GET', '/api/checklists'],
    ['POST', '/api/checklists'],
    ['GET', '/api/checklists/1'],
    ['PUT', '/api/checklists/1'],
    ['PATCH', '/api/checklists/1'],
    ['DELETE', '/api/checklists/1'],
    ['PUT', '/api/checklists/1/position/1'],
    ['GET', '/api/checklists/1/items'],
    ['POST', '/api/checklists/1/items'],
    ['GET', '/api/checklists/1/items/1'],
    ['PUT', '/api/checklists/1/items/1'],
    ['DELETE', '/api/checklists/1/items/1'],
    ['PUT', '/api/checklists/1/items'],
    ['POST', '/api/fcm-token'],
    ['POST', '/api/send-test-notification'],
    ['DELETE', '/api/fcm-token/token'],
    ['GET', '/api/cards/1/comments'],
    ['POST', '/api/cards/1/comments'],
    ['GET', '/api/comments/1'],
    ['PUT', '/api/comments/1'],
    ['PATCH', '/api/comments/1'],
    ['DELETE', '/api/comments/1'],
    ['GET', '/api/cards/1/reminders'],
    ['POST', '/api/cards/1/reminders'],
    ['GET', '/api/reminders/1'],
    ['PUT', '/api/reminders/1'],
    ['PATCH', '/api/reminders/1'],
    ['DELETE', '/api/reminders/1'],
    ['POST', '/api/reminders/process'],
]);

it('requires authentication for every protected feature route', function (string $method, string $uri) {
    $response = $this->json($method, $uri);

    $response->assertUnauthorized();
})->with('protected_routes');
